[2024-07-14T05:18:12.794+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T05:18:12.811+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: glue_etl_pipeline.start_glue_crawler manual__2024-07-14T05:18:11.958823+00:00 [queued]>
[2024-07-14T05:18:12.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: glue_etl_pipeline.start_glue_crawler manual__2024-07-14T05:18:11.958823+00:00 [queued]>
[2024-07-14T05:18:12.823+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T05:18:12.841+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start_glue_crawler> on 2024-07-14 05:18:11.958823+00:00
[2024-07-14T05:18:12.846+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T05:18:12.847+0000] {standard_task_runner.py:63} INFO - Started process 938 to run task
[2024-07-14T05:18:12.847+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'glue_etl_pipeline', 'start_glue_crawler', 'manual__2024-07-14T05:18:11.958823+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/etl_populate_database.py', '--cfg-path', '/tmp/tmpkwdl70xs']
[2024-07-14T05:18:12.848+0000] {standard_task_runner.py:91} INFO - Job 249: Subtask start_glue_crawler
[2024-07-14T05:18:12.885+0000] {task_command.py:426} INFO - Running <TaskInstance: glue_etl_pipeline.start_glue_crawler manual__2024-07-14T05:18:11.958823+00:00 [running]> on host e900ffca6a6f
[2024-07-14T05:18:12.958+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='glue_etl_pipeline' AIRFLOW_CTX_TASK_ID='start_glue_crawler' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T05:18:11.958823+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T05:18:11.958823+00:00'
[2024-07-14T05:18:12.959+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T05:18:12.971+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T05:18:12.972+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_populate_database.py", line 33, in start_crawler
    client = hook.get_client_type('glue', region_name='us-east-2')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AwsGenericHook.get_client_type() got multiple values for argument 'region_name'
[2024-07-14T05:18:12.982+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=glue_etl_pipeline, task_id=start_glue_crawler, run_id=manual__2024-07-14T05:18:11.958823+00:00, execution_date=20240714T051811, start_date=20240714T051812, end_date=20240714T051812
[2024-07-14T05:18:12.993+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 249 for task start_glue_crawler (AwsGenericHook.get_client_type() got multiple values for argument 'region_name'; 938)
[2024-07-14T05:18:13.021+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T05:18:13.041+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T05:18:13.043+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
