[2024-07-16T07:13:54.293+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T07:13:54.316+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: glue_crawler_etl_pipeline.start_glue_job manual__2024-07-16T07:09:02.837883+00:00 [queued]>
[2024-07-16T07:13:54.327+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: glue_crawler_etl_pipeline.start_glue_job manual__2024-07-16T07:09:02.837883+00:00 [queued]>
[2024-07-16T07:13:54.328+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-16T07:13:54.342+0000] {taskinstance.py:2330} INFO - Executing <Task(GlueJobOperator): start_glue_job> on 2024-07-16 07:09:02.837883+00:00
[2024-07-16T07:13:54.346+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2394) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T07:13:54.348+0000] {standard_task_runner.py:63} INFO - Started process 2395 to run task
[2024-07-16T07:13:54.348+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'glue_crawler_etl_pipeline', 'start_glue_job', 'manual__2024-07-16T07:09:02.837883+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/etl_populate_database.py', '--cfg-path', '/tmp/tmppuduiziz']
[2024-07-16T07:13:54.349+0000] {standard_task_runner.py:91} INFO - Job 278: Subtask start_glue_job
[2024-07-16T07:13:54.386+0000] {task_command.py:426} INFO - Running <TaskInstance: glue_crawler_etl_pipeline.start_glue_job manual__2024-07-16T07:09:02.837883+00:00 [running]> on host 0ec6e6e2bd09
[2024-07-16T07:13:54.457+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='glue_crawler_etl_pipeline' AIRFLOW_CTX_TASK_ID='start_glue_job' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T07:09:02.837883+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T07:09:02.837883+00:00'
[2024-07-16T07:13:54.459+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T07:13:54.470+0000] {glue.py:186} INFO - Initializing AWS Glue Job: etl_s3_to_redshift. Wait for completion: True
[2024-07-16T07:13:54.471+0000] {glue.py:365} INFO - Checking if job already exists: etl_s3_to_redshift
[2024-07-16T07:13:54.480+0000] {base_aws.py:587} WARNING - Unable to find AWS Connection ID 'aws_default', switching to empty.
[2024-07-16T07:13:54.481+0000] {base_aws.py:164} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name='us-east-2'). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-07-16T07:13:54.788+0000] {glue.py:191} ERROR - Failed to run aws glue job, error: Unable to locate credentials
[2024-07-16T07:13:54.789+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T07:13:54.789+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 191, in execute
    glue_job_run = self.glue_job_hook.initialize_job(self.script_args, self.run_job_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 187, in initialize_job
    job_name = self.get_or_create_glue_job()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 406, in get_or_create_glue_job
    if self.has_job(self.job_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 368, in has_job
    self.conn.get_job(JobName=job_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1001, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1027, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/signers.py", line 199, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2024-07-16T07:13:54.799+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=glue_crawler_etl_pipeline, task_id=start_glue_job, run_id=manual__2024-07-16T07:09:02.837883+00:00, execution_date=20240716T070902, start_date=20240716T071354, end_date=20240716T071354
[2024-07-16T07:13:54.811+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 278 for task start_glue_job (Unable to locate credentials; 2395)
[2024-07-16T07:13:54.843+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T07:13:54.862+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T07:13:54.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
